//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invent_Petrov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Table
    {
        public int id { get; set; }
        public int id_role { get; set; }
        public string FIO { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public int PassSer { get; set; }
        public int PassNum { get; set; }
        public System.DateTime DateBirth { get; set; }
        public Nullable<System.DateTime> LastWel { get; set; }
        public Nullable<int> id_wel { get; set; }
        public int id_gen { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Role Role { get; set; }
        public virtual Wel Wel { get; set; }
    }
}
